### ISSUE TITLE
你好，请问数据集可以提供吗

### ISSUE THREAD

**Issue by wangbq18** [luanshiyinyang/ChineseOCR#1]
如题

**Comment by luanshiyinyang** [comment]
你好，这是我的一个比赛项目，数据集https://aistudio.baidu.com/aistudio/datasetdetail/8429

**Comment by wangbq18** [comment]
> 
> 
> 你好，这是我的一个比赛项目，数据集https://aistudio.baidu.com/aistudio/datasetdetail/8429

谢谢
