### ISSUE TITLE
关于模型

### ISSUE THREAD

**Issue by SCU-Feng** [luanshiyinyang/ChineseOCR#2]
你好！
      很感谢你的分享，你做出的尝试对大家很有参考价值。但是我对模型的效果有一些疑问，请问你的模型打比赛的效果如何，不知可否分享？

**Comment by luanshiyinyang** [comment]
我们团队后面进行了一些尝试，由于比赛数据集可以直接进行流程的最后一步（这是基于绝大多数图片不需要进行方向检测和文本区域识别的），将调整好长宽的图片直接送入CNN+LSTM+CTC的识别网络，验证集行准确率可以达到80 %左右，但是由于后期团队成员确实都比较忙，所以这个比赛并没有进行提交，如果你想了解高分的模型及源码，可以到AI Studio的比赛区查看，比赛名就是中文场景的文字识别（目前还没有结束）。

**Comment by SCU-Feng** [comment]
非常感谢你的分享，谢谢



---原始邮件---
发件人: "zhouchen"<notifications@github.com&gt;
发送时间: 2019年10月12日(星期六) 上午9:48
收件人: "luanshiyinyang/ChineseOCR"<ChineseOCR@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"SCU-Feng"<503056728@qq.com&gt;;
主题: Re: [luanshiyinyang/ChineseOCR] 关于模型 (#2)



我们团队后面进行了一些尝试，由于比赛数据集可以直接进行流程的最后一步（这是基于绝大多数图片不需要进行方向检测和文本区域识别的），将调整好长宽的图片直接送入CNN+LSTM+CTC的识别网络，验证集行准确率可以达到80 %左右，但是由于后期团队成员确实都比较忙，所以这个比赛并没有进行提交，如果你想了解高分的模型及源码，可以到AI Studio的比赛区查看，比赛名就是中文场景的文字识别（目前还没有结束）。
